auto_gestion_beta/applications/reports/urls.py
from django.urls import path
from . import views
from .views import *
from django.views.generic import TemplateView

app_name = "reportes"

urlpatterns = [
    #path('generar_consulta/', generar_consulta, name='generar_consulta'),
    #path('vista-de-prueba/', consulta_view, name='prueba'),
    path('columnas/', columnas_view, name='column_Selection'),
    path('filter/', filtro_view, name='filter_Selection'),
    path('consula/', consulta_view, name='consult'),
]

auto_gestion_beta/auto_gestion_beta/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # Otras rutas
    path('reports/', include('applications.reports.urls')),
]

auto_gestion_beta/applications/reports/models.py
from django.db import models


# Create your models here.
class FormBasic(models.Model):
    Identificacion = models.IntegerField()
    Identificacion_corp = models.IntegerField()
    Tipo_doc = models.CharField(max_length=255)
    NOMBRES = models.CharField(max_length=255)
    APELLIDOS = models.CharField(max_length=255)
    DIRECCION = models.CharField(max_length=255)
    CIUDAD = models.CharField(max_length=255)
    ESPECIALIDAD = models.CharField(max_length=255)
    CONTACTABLE_SODIMAC = models.CharField(max_length=20)
    CONTACTABLE_TERCERO = models.CharField(max_length=20)
    CANAL_OPTIN = models.CharField(max_length=255)
    FECHA_AUTORIZACION = models.CharField(max_length=255)
    PERIODO_SEGMENTACION = models.CharField(max_length=255)
    PERFIL_SEGMENTACION = models.CharField(max_length=255)
    SEGMENTO_NECESIDAD = models.CharField(max_length=255)
    SEGMENTO_VALOR = models.CharField(max_length=255)
    CICLO_VIDA = models.CharField(max_length=255)
    TIENDA_FRECUENTE = models.CharField(max_length=255)
    FAMILIA_MAYOR_FRECUENCIA = models.CharField(max_length=255)
    TIPO_SEGMENTO = models.CharField(max_length=255)
    PIRAMIDE = models.CharField(max_length=255)
    GENERO = models.CharField(max_length=255)
    FECHA_NACIMIENTO = models.CharField(max_length=255)
    ESTADO_CES = models.CharField(max_length=255)
    PROFESION = models.CharField(max_length=255)
    SEGMENTO_CES = models.CharField(max_length=255)
    FECHA_NIVEL = models.CharField(max_length=255)
    FECHA_INICIAL_CES = models.CharField(max_length=255)
    FECHA_FIN_CES = models.CharField(max_length=255)
    CREATED_AT = models.CharField(max_length=255)
    FECHA_INSCRIPCION_CMR = models.CharField(max_length=255)
    TOTPUNTO = models.IntegerField()
    RANGO_PUNTOS = models.CharField(max_length=255)
    PUNTOS_REDIMIDOS_12M = models.CharField(max_length=255)
    MARCA_TDC = models.CharField(max_length=255)
    MARCA_TDB = models.CharField(max_length=255)
    CLIENTE_ACTIVO = models.CharField(max_length=255)
    FECHA_ULTIMA_COMPRA = models.CharField(max_length=255)
    CANAL_VD_ULTIMA_COMPRA = models.CharField(max_length=255)
    TIENDA_DESPACHA_ULTIMA_COMPRA = models.CharField(max_length=255)
    MEDIO_PAGO_ULTIMA_COMPRA = models.CharField(max_length=255)
    FLAG_CMR_PUNTOS = models.CharField(max_length=255)
    FLAG_BANCO = models.CharField(max_length=255)   
    FLAG_CEC = models.CharField(max_length=255)
    FLAG_CLIENTE360 = models.CharField(max_length=255)
    FLAG_SEGMENTADOS = models.CharField(max_length=255)
    FLAG_COMPRADORES_ACTIVOS = models.CharField(max_length=255)
    FLAG_COMPRADORES_MES_CORTE = models.CharField(max_length=255)
    FLAG_COMPRADORES_ACUMULADOS = models.CharField(max_length=255)
    FLAG_LOYALTY = models.CharField(max_length=255)

    class Meta:
        verbose_name = "FormBasic"
        verbose_name_plural = "FormBasics"

    def __str__(self):
        return self.id

auto_gestion_beta/applications/reports/views.py
from django.shortcuts import render
from google.cloud import bigquery
import pandas as pd
import json
import re
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from .RegexBasic import RegexBasic
from datetime import datetime
from unipath import Path
from google.cloud import storage
import os
from .forms import *
from django.shortcuts import render, redirect

 

def consultar_datos(request, tabla):
    # Crea un cliente de BigQuery
    client = bigquery.Client()

    # Construye la consulta utilizando el nombre de la tabla especificado en la URL
    query = f"SELECT * FROM `driven-atrium-400420.sod_co_bi_reportsmanagement_dev.{tabla}`"

    # Ejecuta la consulta en BigQuery
    query_job = client.query(query)

    # Recupera los resultados
    results = query_job.result()

    # Obtener los nombres de las columnas desde el esquema de BigQuery
    column_names = [field.name for field in results.schema]

    # Convierte los resultados en un DataFrame
    data = [list(row.values()) for row in results]
    df = pd.DataFrame(data, columns=column_names)
    # Definir las palabras clave para buscar en los nombres de las columnas
    palabras_clave = ['VENTA', 'FACTURA', 'TICKET']  # Puedes agregar otras palabras clave

    # Aplicar el formato de dinero a columnas que contengan las palabras clave
    #for palabra in palabras_clave:
    #    patron = re.compile(f'.*{palabra}.*', re.IGNORECASE)
    #   columnas_coincidentes = [col for col in df.columns if patron.match(col)]
    #    for col in columnas_coincidentes:
    #        df[col] = df[col].map('${:,.2f}'.format)

    # Asegúrate de que las fechas estén formateadas correctamente como objetos de fecha
    df['fecha'] = pd.to_datetime(df['fecha'])

    # Convierte las fechas a cadenas de texto
    df['fecha'] = df['fecha'].dt.strftime('%Y-%m-%d %H:%M:%S')
    print(df.dtypes)
    # Convierte el DataFrame a una lista de diccionarios
    data_json = df.to_dict(orient='records')

    # Guarda los datos en un archivo JSON (opcional)
    with open('datos.json', 'w') as json_file:
        json.dump(data_json, json_file)

    return render(request, 'consulta.html', {'data': data_json})



##Adaptar al código (Sin adaptar)
class SingleInformation():
    def __init__(self,js):
        super().__init__()
        self.campaign_id = js["identificacion"]
        self.campaign_date = js["identificacion_corp"]
        
    def retrieve_campaign(self):
        client = bigquery.Client()
        query = f"""
        SELECT * FROM `driven-atrium-400420.sod_co_bi_reportsmanagement_dev.CLIENTES_DIM`
        """
        response = client.query(query)
        response.result()
        response = response.to_dataframe()  
        return response["nombre"][0]
    
### Adaptar al código (Sin adaptar. )    
class Procedimientos:
    def __init__(self, js):
        # Ajusta el nombre del atributo js a minúsculas para que coincida con las columnas de BigQuery
        self.Identificacion = js.get("Identificacion", None)
        self.Identificacion_corp = js.get("Identificacion_corp", None)
        self.Tipo_doc = js.get("Tipo_doc", None)
        self.NOMBRES = js.get("NOMBRES", None)
        self.APELLIDOS = js.get("APELLIDOS", None)
        self.DIRECCION = js.get("DIRECCION", None)
        self.CIUDAD = js.get("CIUDAD", None)
        self.ESPECIALIDAD = js.get("ESPECIALIDAD", None)
        self.CONTACTABLE_SODIMAC = js.get("CONTACTABLE_SODIMAC", None)
        self.CONTACTABLE_TERCERO = js.get("CONTACTABLE_TERCERO", None)
        self.CANAL_OPTIN = js.get("CANAL_OPTIN", None)
        self.FECHA_AUTORIZACION = js.get("FECHA_AUTORIZACION", None)
        self.PERIODO_SEGMENTACION = js.get("periodo_segmentacion", None)
        self.PERFIL_SEGMENTACION = js.get("perfil_segmentacion", None)
        self.SEGMENTO_NECESIDAD = js.get("segmento_necesidad", None)
        self.SEGMENTO_VALOR = js.get("segmento_valor", None)
        self.CICLO_VIDA = js.get("ciclo_vida", None)
        self.TIENDA_FRECUENTE = js.get("tienda_frecuente", None)
        self.FAMILIA_MAYOR_FRECUENCIA = js.get("familia_mayor_frecuencia", None)
        self.TIPO_SEGMENTO = js.get("tipo_segmento", None)
        self.PIRAMIDE = js.get("piramide", None)
        self.GENERO = js.get("genero", None)
        self.FECHA_NACIMIENTO = js.get("fecha_nacimiento", None)
        self.ESTADO_CES = js.get("estado_ces", None)
        self.PROFESION = js.get("profesion", None)
        self.SEGMENTO_CES = js.get("segmento_ces", None)
        self.FECHA_NIVEL = js.get("fecha_nivel", None)
        self.FECHA_INICIAL_CES = js.get("fecha_inicial_ces", None)
        self.FECHA_FIN_CES = js.get("fecha_fin_ces", None)
        self.CREATED_AT = js.get("created_at", None)
        self.FECHA_INSCRIPCION_CMR = js.get("fecha_inscripcion_cmr", None)
        self.TOTPUNTO = js.get("totpunto", None)
        self.RANGO_PUNTOS = js.get("rango_puntos", None)
        self.PUNTOS_REDIMIDOS_12M = js.get("puntos_redimidos_12m", None)
        self.MARCA_TDC = js.get("marca_tdc", None)
        self.MARCA_TDB = js.get("marca_tdb", None)
        self.CLIENTE_ACTIVO = js.get("cliente_activo", None)
        self.FECHA_ULTIMA_COMPRA = js.get("fecha_ultima_compra", None)
        self.CANAL_VD_ULTIMA_COMPRA = js.get("canal_vd_ultima_compra", None)
        self.TIENDA_DESPACHA_ULTIMA_COMPRA = js.get("tienda_despacha_ultima_compra", None)
        self.MEDIO_PAGO_ULTIMA_COMPRA = js.get("medio_pago_ultima_compra", None)
        self.FLAG_CMR_PUNTOS = js.get("flag_cmr_puntos", None)
        self.FLAG_BANCO = js.get("flag_banco", None)
        self.FLAG_CEC = js.get("flag_cec", None)
        self.FLAG_CLIENTE360 = js.get("flag_cliente360", None)
        self.FLAG_SEGMENTADOS = js.get("flag_segmentados", None)
        self.FLAG_COMPRADORES_ACTIVOS = js.get("flag_compradores_activos", None)
        self.FLAG_COMPRADORES_MES_CORTE = js.get("flag_compradores_mes_corte", None)
        self.FLAG_COMPRADORES_ACUMULADOS = js.get("flag_compradores_acumulados", None)
        self.FLAG_LOYALTY = js.get("flag_loyalty", None)

    def _generar_clausulas_where(self, **campos):
        return [f"{campo} = '{valor}'" for campo, valor in campos.items() if valor is not None and valor not in ('', '*')]

    def _generar_clausulas_select(self, selected_columns):
    # Ajusta los nombres y añade más campos según sea necesario
        select_clauses = [column for column in selected_columns if column != "Seleccionar Todas"]

        return select_clauses
        
    def generar_consulta_BigQuery(self, selected_columns):
        select_clause = ", ".join(self._generar_clausulas_select(selected_columns))
        where_clauses = self._generar_clausulas_where(
            Identificacion=self.Identificacion,
            Identificacion_corp=self.Identificacion_corp,
            Tipo_doc=self.Tipo_doc,
            NOMBRES=self.NOMBRES,
            APELLIDOS=self.APELLIDOS,
            DIRECCION=self.DIRECCION,
            CIUDAD=self.CIUDAD,
            ESPECIALIDAD=self.ESPECIALIDAD,
            CONTACTABLE_SODIMAC=self.CONTACTABLE_SODIMAC,
            CONTACTABLE_TERCERO=self.CONTACTABLE_TERCERO,
            CANAL_OPTIN=self.CANAL_OPTIN,
            FECHA_AUTORIZACION=self.FECHA_AUTORIZACION,
            PERIODO_SEGMENTACION=self.PERIODO_SEGMENTACION,
            PERFIL_SEGMENTACION=self.PERFIL_SEGMENTACION,
            SEGMENTO_NECESIDAD=self.SEGMENTO_NECESIDAD,
            SEGMENTO_VALOR=self.SEGMENTO_VALOR,
            CICLO_VIDA=self.CICLO_VIDA,
            TIENDA_FRECUENTE=self.TIENDA_FRECUENTE,
            FAMILIA_MAYOR_FRECUENCIA=self.FAMILIA_MAYOR_FRECUENCIA,
            TIPO_SEGMENTO=self.TIPO_SEGMENTO,
            PIRAMIDE=self.PIRAMIDE,
            GENERO=self.GENERO,
            FECHA_NACIMIENTO=self.FECHA_NACIMIENTO,
            ESTADO_CES=self.ESTADO_CES,
            PROFESION=self.PROFESION,
            SEGMENTO_CES=self.SEGMENTO_CES,
            FECHA_NIVEL=self.FECHA_NIVEL,
            FECHA_INICIAL_CES=self.FECHA_INICIAL_CES,
            FECHA_FIN_CES=self.FECHA_FIN_CES,
            CREATED_AT=self.CREATED_AT,
            FECHA_INSCRIPCION_CMR=self.FECHA_INSCRIPCION_CMR,
            TOTPUNTO=self.TOTPUNTO,
            RANGO_PUNTOS=self.RANGO_PUNTOS,
            PUNTOS_REDIMIDOS_12M=self.PUNTOS_REDIMIDOS_12M,
            MARCA_TDC=self.MARCA_TDC,
            MARCA_TDB=self.MARCA_TDB,
            CLIENTE_ACTIVO=self.CLIENTE_ACTIVO,
            FECHA_ULTIMA_COMPRA=self.FECHA_ULTIMA_COMPRA,
            CANAL_VD_ULTIMA_COMPRA=self.CANAL_VD_ULTIMA_COMPRA,
            TIENDA_DESPACHA_ULTIMA_COMPRA=self.TIENDA_DESPACHA_ULTIMA_COMPRA,
            MEDIO_PAGO_ULTIMA_COMPRA=self.MEDIO_PAGO_ULTIMA_COMPRA,
            FLAG_CMR_PUNTOS=self.FLAG_CMR_PUNTOS,
            FLAG_BANCO=self.FLAG_BANCO,
            FLAG_CEC=self.FLAG_CEC,
            FLAG_CLIENTE360=self.FLAG_CLIENTE360,
            FLAG_SEGMENTADOS=self.FLAG_SEGMENTADOS,
            FLAG_COMPRADORES_ACTIVOS=self.FLAG_COMPRADORES_ACTIVOS,
            FLAG_COMPRADORES_MES_CORTE=self.FLAG_COMPRADORES_MES_CORTE,
            FLAG_COMPRADORES_ACUMULADOS=self.FLAG_COMPRADORES_ACUMULADOS,
            FLAG_LOYALTY=self.FLAG_LOYALTY,
        )# Construye la consulta SQL
        query = f"SELECT {select_clause} FROM `driven-atrium-400420.sod_co_bi_reportsmanagement_dev.CLIENTES_DIM`"

        # Añade las cláusulas WHERE si existen
        if where_clauses:
            query += " WHERE " + " AND ".join(where_clauses)

        #try:
        #    # Ejecuta la consulta en BigQuery
        #    client = bigquery.Client()
        #    query_job = client.query(query)

            # Obtiene los resultados
        #    results = query_job.result()

            # Retorna los resultados (o ajusta según sea necesario)
        #    return HttpResponse(f"Query ejecutada correctamente. Resultados: {results}")
        #except Exception as e:
            # Maneja cualquier error y retorna una respuesta adecuada

auto_gestion_beta/applications/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autogestión de reportes</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Barra de navegación superior -->
    <header>
        <nav>
            <!-- Botón para desplegar/colapsar la barra lateral -->
            <button id="toggle-sidebar">
                <i class="fas fa-bars"></i>
            </button>
            <!-- Otros elementos de navegación, si los hay -->
        </nav>
    </header>

    <!-- Barra lateral colapsable -->
    <aside id="sidebar">
        <!-- Contenido de la barra lateral, como filtros, enlaces, etc. -->
    </aside>

    <!-- Contenido principal -->
    <main>
        <!-- Contenido principal iría aquí, pero no se proporciona en esta versión -->
        {%block content%}

        {%endblock content%}
    </main>

    <!-- Script para controlar el colapso de la barra lateral -->
    <script src="{% static 'js/barra.js' %}"></script>
</body>
</html>

auto_gestion_beta/applications/templates/columnas.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Seleccionar Columnas</h2>
        <form id="ColumnSelectionForm" action="{% url 'reportes:column_Selection' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Siguiente</button>
        </form>
    </div>

    <script>
        function enviarFormulario() {
            var formData = new FormData(document.getElementById('FormBasicForm'));

            fetch('{% url "reportes:column_Selection" %}', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                console.log('Respuesta del servidor:', data);
                // Manejar la respuesta y actualizar la interfaz de usuario, por ejemplo:
                document.getElementById('resultados').innerHTML = 'Resultados: ' + data.resultado;
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
{% endblock %}

auto_gestion_beta/applications/templates/consulta.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autogestión de reportes</title>
    <!-- Configuración del favicon para la pestaña del navegador -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Barra de navegación superior -->
    <header>
        <nav>
            <!-- Botón para desplegar/colapsar la barra lateral -->
            <button id="toggle-sidebar">
                <i class="fas fa-bars"></i>
            </button>
            <!-- Otros elementos de navegación, si los hay -->
        </nav>
    </header>

    <!-- Barra lateral colapsable -->
    <aside id="sidebar">
        <!-- No hay contenido en la barra lateral en esta versión -->
    </aside>

    <!-- Contenido principal -->
    <main>
        <!-- Espacio para filtrar y presentar la tabla -->
        <div class="table-container">
            <!-- No incluyas la tabla ni otros elementos relacionados -->
            <!-- Incluye solo el contenido de los filtros -->
            {% include 'filtros.html' %}
        </div>
    </main>

    <!-- Script para controlar el colapso de la barra lateral y aplicar filtros -->
    <script src="{% static 'js/filtros.js' %}"></script>
</body>
</html>

auto_gestion_beta/applications/templates/filtros.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Generar Consulta</h2>
        <form id="FormBasicForm" action="{% url 'reportes:column_Selection' %}" method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit">Enviar</button>
        </form>
        <div id="resultados">
            <!-- Aquí se mostrarán los resultados de la consulta -->
        </div>
    </div>

    <script>
        function enviarFormulario() {
            var formData = new FormData(document.getElementById('FormBasicForm'));

            fetch('{% url "reportes:filter_Selection" %}', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                console.log('Respuesta del servidor:', data);
                // Manejar la respuesta y actualizar la interfaz de usuario, por ejemplo:
                document.getElementById('resultados').innerHTML = 'Resultados: ' + data.resultado;
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
{% endblock %}

auto_gestion_beta/applications/templates/icons.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iconos</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <h1>Iconos</h1>

    <!-- Ejemplos de iconos -->
    <i class="fas fa-home"></i>
    <i class="fas fa-user"></i>
    <i class="fas fa-cog"></i>
    <!-- Agrega más iconos según sea necesario -->

</body>
</html>